import 'package:flutter/material.dart';

class ChatScenario {
  final String title;
  final String description;
  final IconData icon;
  final List<Map<String, dynamic>> messages;

  ChatScenario({
    required this.title,
    required this.description,
    required this.icon,
    required this.messages,
  });
}

final List<ChatScenario> chatScenarios = [
  ChatScenario(
    title: 'Cumprimentos e Amizade',
    description: 'Aprenda a fazer amigos e manter conversas casuais em espanhol.',
    icon: Icons.waving_hand_rounded,
    messages: [
      {'isBot': true, 'en': '¡Hola! Es un placer conhecerte.', 'pt': 'Olá! É muito bom conhecer você.'},
      {'isBot': false, 'en': '¡Hola! Encantado de conocerte también. Me llamo Alex.', 'pt': 'Oi! Prazer em conhecê-lo também. Meu nome é Alex.'},
      {'isBot': true, 'en': '¿De dónde eres, Alex?', 'pt': 'De onde você é, Alex?'},
      {'isBot': false, 'en': 'Soy de Brasil. ¿Y tú?', 'pt': 'Eu sou do Brasil. E você?'},
      {'isBot': true, 'en': 'Soy de los Estados Unidos. ¿Te gusta la ciudad?', 'pt': 'Eu sou dos Estados Unidos. Você está gostando da cidade?'},
      {'isBot': false, 'en': 'Sí, es muy hermoso aquí.', 'pt': 'Sim, é muito bonito aqui.'},
      {'isBot': true, 'en': 'Qué bien. ¿Hace cuánto tempo estás aquí?', 'pt': 'Isso é ótimo. Há quanto tempo você está aqui?'},
      {'isBot': false, 'en': 'Llegué hace tres dias.', 'pt': 'Eu cheguei há três dias atrás.'},
      {'isBot': true, 'en': '¿Ya has visitado el museo local?', 'pt': 'Você já visitou o museu local?'},
      {'isBot': false, 'en': 'Aún no. ¿Es bueno?', 'pt': 'Ainda não. É bom?'},
      {'isBot': true, 'en': 'Sí, la colección de arte es increíble.', 'pt': 'Sim, a coleção de arte é incrível.'},
      {'isBot': false, 'en': 'Sin duda iré allí mañana.', 'pt': 'Eu com certeza irei lá amanhã.'},
      {'isBot': true, 'en': '¿Te gustaría compañía?', 'pt': 'Você gostaria de companhia?'},
      {'isBot': false, 'en': 'Claro, ¡sería maravilhoso!', 'pt': 'Claro, isso seria maravilhoso!'},
      {'isBot': true, 'en': '¡Perfecto! ¿Nos encontramos a las 10?', 'pt': 'Perfeito! Vamos nos encontrar às 10 da manhã?'},
      {'isBot': false, 'en': 'Las 10 de la mañana está perfecto para mí.', 'pt': 'Dez da manhã é ótimo para mim.'},
      {'isBot': true, 'en': 'Genial. Déjame darte mi número.', 'pt': 'Incrível. Deixe-me dar o meu número de telefone.'},
      {'isBot': false, 'en': 'Gracias. Te llamaré si me pierdo.', 'pt': 'Obrigado. Eu te ligo se eu me perder.'},
      {'isBot': true, 'en': 'No te preocupes, es muy fácil de encontrar.', 'pt': 'Não se preocupe, é muito fácil de encontrar.'},
      {'isBot': false, 'en': 'Hasta mañana entonces. ¡Adiós!', 'pt': 'Te vejo amanhã então. Tchau!'},
    ],
  ),
  ChatScenario(
    title: 'No Aeroporto',
    description: 'Conversação prática para check-in e segurança em espanhol.',
    icon: Icons.flight_takeoff_rounded,
    messages: [
      {'isBot': true, 'en': 'Buenos días. ¿Puedo ver su pasaporte y su pasaje, por favor?', 'pt': 'Bom dia. Posso ver seu passaporte e passagem, por favor?'},
      {'isBot': false, 'en': 'Buenos días. Sí, aquí los tiene.', 'pt': 'Bom dia. Sim, aqui estão.'},
      {'isBot': true, 'en': 'Gracias. ¿A dónde viaja hoy?', 'pt': 'Obrigado. Para onde você está voando hoje?'},
      {'isBot': false, 'en': 'Viajo a Nueva York.', 'pt': 'Estou voando para Nova Iorque.'},
      {'isBot': true, 'en': '¿Va a facturar equipaje?', 'pt': 'Você vai despachar alguma mala?'},
      {'isBot': false, 'en': 'Sí, tengo una maleta.', 'pt': 'Sim, eu tenho uma mala.'},
      {'isBot': true, 'en': 'Por favor, colóquela en la báscula.', 'pt': 'Por favor, coloque-a na balança.'},
      {'isBot': false, 'en': 'Claro. ¿Supera el límite de peso?', 'pt': 'Claro. Está com excesso de peso?'},
      {'isBot': true, 'en': 'No, está perfecto. ¿Prefiere asiento de pasillo o de ventana?', 'pt': 'Não, está perfeitamente bem. Gostaria de assento no corredor ou janela?'},
      {'isBot': false, 'en': 'De ventana, por favor.', 'pt': 'Um assento na janela, por favor.'},
      {'isBot': true, 'en': 'Muy bien. Aquí tiene su tarjeta de embarque.', 'pt': 'Certo. Aqui está seu cartão de embarque.'},
      {'isBot': false, 'en': 'Gracias. ¿Qué puerta es?', 'pt': 'Obrigado. Qual é o portão?'},
      {'isBot': true, 'en': 'Su puerta es la B12. El embarque comienza a las 14 horas.', 'pt': 'Seu portão é o B12. O embarque começa às 2 da tarde.'},
      {'isBot': false, 'en': '¿Dónde está el control de seguridad?', 'pt': 'E onde é a verificação de segurança?'},
      {'isBot': true, 'en': 'La seguridad está justo a la vuelta de la esquina a su izquierda.', 'pt': 'A segurança fica virando a esquina à sua esquerda.'},
      {'isBot': false, 'en': '¿Tengo que quitarme los zapatos?', 'pt': 'Preciso tirar meus sapatos?'},
      {'isBot': true, 'en': 'Sí, por favor quítese los zapatos y la chaqueta.', 'pt': 'Sim, por favor remova seus sapatos e jaquetas.'},
      {'isBot': false, 'en': 'De acuerdo, lo haré.', 'pt': 'Certo, farei isso.'},
      {'isBot': true, 'en': '¡Buen vuelo!', 'pt': 'Tenha um voo seguro!'},
      {'isBot': false, 'en': '¡Gracias! Buen día.', 'pt': 'Obrigado! Tenha um bom dia.'},
    ],
  ),
  ChatScenario(
    title: 'No Restaurante',
    description: 'Do pedido da comida até o momento de pagar a conta em espanhol.',
    icon: Icons.restaurant_rounded,
    messages: [
      {'isBot': true, 'en': '¡Bienvenido! ¿Una mesa para una persona?', 'pt': 'Bem-vindo! Uma mesa para um?'},
      {'isBot': false, 'en': 'Sí, por favor. Cerca de la ventana si es posible.', 'pt': 'Sim, por favor. Perto da janela, se possível.'},
      {'isBot': true, 'en': 'Por aquí. Aquí tiene su menú.', 'pt': 'Por aqui. Aqui está o seu menu.'},
      {'isBot': false, 'en': 'Gracias. ¿Puedo tomar un vaso de agua?', 'pt': 'Obrigado(a). Posso tomar um copo de água?'},
      {'isBot': true, 'en': 'Claro. ¿Está listo para ordenar ahora?', 'pt': 'Claro. Você está pronto para fazer o pedido agora?'},
      {'isBot': false, 'en': 'Necesito unos minutos más, por favor.', 'pt': 'Preciso de mais alguns minutos, por favor.'},
      {'isBot': true, 'en': 'Tómese su tiempo. Avíseme cuando esté listo.', 'pt': 'Fique à vontade. Me avise quando estiver pronto.'},
      {'isBot': false, 'en': 'De acuerdo. Estoy listo para ordenar.', 'pt': 'Certo. Estou pronto para pedir.'},
      {'isBot': true, 'en': '¿Qué le gustaría comer hoy?', 'pt': 'O que você gostaria hoje?'},
      {'isBot': false, 'en': 'Voy a querer pollo a la plancha con ensalada.', 'pt': 'Eu vou querer o frango grelhado com salada.'},
      {'isBot': true, 'en': 'Excelente elección. ¿Algún aderezo para la ensalada?', 'pt': 'Excelente escolha. Algum molho para a salada?'},
      {'isBot': false, 'en': 'Solo aceite de oliva y limón, gracias.', 'pt': 'Apenas azeite e limão, obrigado(a).'},
      {'isBot': true, 'en': '¿Y le gustaría algo para beber?', 'pt': 'E gostaria de algo para beber?'},
      {'isBot': false, 'en': 'Un vaso de jugo de naranja, por favor.', 'pt': 'Um copo de suco de laranja, por favor.'},
      {'isBot': true, 'en': 'Su comida estará lista en 15 minutos.', 'pt': 'Sua comida estará pronta em 15 minutos.'},
      {'isBot': false, 'en': 'Perfecto, tengo mucha hambre.', 'pt': 'Perfeito, estou com muita fome.'},
      {'isBot': true, 'en': 'Aquí tiene su comida. ¡Buen provecho!', 'pt': 'Aqui está sua refeição. Aproveite!'},
      {'isBot': false, 'en': 'Tiene una pinta deliciosa. ¿Me trae la cuenta, por favor?', 'pt': 'Parece delicioso. Pode me trazer a conta, por favor?'},
      {'isBot': true, 'en': 'Claro. ¿Cómo desea pagar?', 'pt': 'Certamente. Como você gostaria de pagar?'},
      {'isBot': false, 'en': 'Pagaré con tarjeta de crédito.', 'pt': 'Eu pagarei com cartão de crédito.'},
    ],
  ),
  ChatScenario(
    title: 'Compras e Lojas',
    description: 'Aprenda expressões para provar e comprar produtos em espanhol.',
    icon: Icons.shopping_bag_rounded,
    messages: [
      {'isBot': true, 'en': '¡Hola! ¿Le puedo ajudar a encontrar algo?', 'pt': 'Olá! Posso ajudar você a encontrar algo?'},
      {'isBot': false, 'en': 'Sí, estoy buscando un abrigo de invierno.', 'pt': 'Sim, estou procurando um casaco de inverno.'},
      {'isBot': true, 'en': 'Nuestros abrigos de invierno están justo aquí. ¿Qué talla?', 'pt': 'Nossos casacos de inverno estão bem aqui. Qual tamanho?'},
      {'isBot': false, 'en': 'Suelo usar la talla M.', 'pt': 'Eu costumo usar médio.'},
      {'isBot': true, 'en': 'Aquí tiene uno azul muy bonito en la talla M. Pruébeselo.', 'pt': 'Aqui tem um azul bonito no tamanho médio. Experimente.'},
      {'isBot': false, 'en': '¿Dónde están los probadores?', 'pt': 'Onde ficam os provadores?'},
      {'isBot': true, 'en': 'Están al fondo de la tienda, a la izquierda.', 'pt': 'Ficam no fundo da loja, à esquerda.'},
      {'isBot': false, 'en': 'Gracias. Voy a probármelo.', 'pt': 'Obrigado. Eu vou experimentar.'},
      {'isBot': true, 'en': '¿Cómo le queda?', 'pt': 'Como serviu?'},
      {'isBot': false, 'en': 'Me queda un poco apretado. ¿Tiene una talla L?', 'pt': 'Ficou um pouco apertado. Você tem um grande?'},
      {'isBot': true, 'en': 'Déjeme comprobar... Sí, aquí tiene uno en la talla L.', 'pt': 'Deixe-me checar... Sim, aqui está um tamanho grande.'},
      {'isBot': false, 'en': 'Este me queda perfecto. ¿Cuánto cuesta?', 'pt': 'Esse serviu perfeitamente. Quanto custa?'},
      {'isBot': true, 'en': 'Cuesta cincuenta y cinco dollars.', 'pt': 'Custa cinquenta e cinco dólares.'},
      {'isBot': false, 'en': '¿Tienen algún descuento hoy?', 'pt': 'Vocês têm algum desconto hoje?'},
      {'isBot': true, 'en': 'Sí, hay un descuento del 10% en toda la ropa de invierno.', 'pt': 'Sim, tem um desconto de 10% em todas roupas de inverno.'},
      {'isBot': false, 'en': 'Eso es genial. Me lo llevo.', 'pt': 'Isso é ótimo. Eu vou levar.'},
      {'isBot': true, 'en': '¿Desea pagar en efectivo o con tarjeta?', 'pt': 'Gostaria de pagar com dinheiro ou cartão?'},
      {'isBot': false, 'en': 'Pagaré en efectivo. Aquí tiene sesenta dólares.', 'pt': 'Pagarei em dinheiro. Aqui estão sessenta dólares.'},
      {'isBot': true, 'en': 'Aquí tiene su cambio y su recibo. ¡Que tenga un buen día!', 'pt': 'Aqui está seu troco e sua nota fiscal. Tenha um bom dia!'},
      {'isBot': false, 'en': 'Muchas gracias. Adiós.', 'pt': 'Muito obrigado. Tchau.'},
    ],
  ),
  ChatScenario(
    title: 'Na Recepção do Hotel',
    description: 'Reservas, check-in e pedidos especiais em espanhol.',
    icon: Icons.hotel_rounded,
    messages: [
      {'isBot': true, 'en': '¡Bienvenido al Grand Hotel! ¿Cómo puedo ayudarle?', 'pt': 'Bem-vindo ao Grand Hotel. Como posso ajudá-lo?'},
      {'isBot': false, 'en': 'Tengo una reserva a nombre de John Smith.', 'pt': 'Eu tenho uma reserva no nome de John Smith.'},
      {'isBot': true, 'en': 'Déjeme comprobar... Ah sí, una habitación sencilla por tres noches. ¿Es correcto?', 'pt': 'Deixe-me checar... Ah sim, um quarto de solteiro por três noites.'},
      {'isBot': false, 'en': 'Es correcto. ¿Está incluido el desayuno?', 'pt': 'Isso está correto. O café da manhã está incluído?'},
      {'isBot': true, 'en': 'Sí, el desayuno se sirve de 7:00 a 10:00.', 'pt': 'Sim, o café da manhã é servido das 7 às 10 da manhã.'},
      {'isBot': false, 'en': 'Excelente. ¿En qué piso está mi habitación?', 'pt': 'Ótimo. Em qual andar fica o meu quarto?'},
      {'isBot': true, 'en': 'Está en el quinto piso, habitación 502.', 'pt': 'Você está no quinto andar, quarto 502.'},
      {'isBot': false, 'en': '¿Hay Wi-Fi gratuito en la habitación?', 'pt': 'Vocês têm Wi-Fi grátis no quarto?'},
      {'isBot': true, 'en': 'Sí, la contraseña está escrita en su tarjeta-llave.', 'pt': 'Sim, a senha está escrita no seu cartão-chave.'},
      {'isBot': false, 'en': '¿Hay gimnasio en el hotel?', 'pt': 'Tem academia no hotel?'},
      {'isBot': true, 'en': 'Sí, el gimnasio está en la planta baja, al lado de la piscina.', 'pt': 'Sim, a academia fica no térreo ao lado da piscina.'},
      {'isBot': false, 'en': '¿Puedo pedir que me despierten por teléfono mañana?', 'pt': 'Posso pedir uma ligação de despertar para amanhã?'},
      {'isBot': true, 'en': 'Claro. ¿A qué hora desea despertarse?', 'pt': 'Claro. A que horas gostaria de acordar?'},
      {'isBot': false, 'en': 'A las seis y media de la mañana, por favor.', 'pt': 'Às seis e meia da manhã, por favor.'},
      {'isBot': true, 'en': 'Anotado. ¿Necesita ayuda con las maletas?', 'pt': 'Anotado. Precisa de ajuda com as malas?'},
      {'isBot': false, 'en': 'No, gracias, puedo arreglármelas solo. ¿Dónde está el ascensor?', 'pt': 'Não obrigado, eu dou conta. Onde é o elevador?'},
      {'isBot': true, 'en': 'Los ascensores están justo detrás de usted.', 'pt': 'Os elevadores estão bem atrás de você.'},
      {'isBot': false, 'en': '¡Gracias! ¿A qué hora es la salida?', 'pt': 'Obrigado! A que horas é o checkout?'},
      {'isBot': true, 'en': 'La salida es a las 11:00. ¡Que tenga una buena estancia!', 'pt': 'O checkout é às 11 da manhã. Aproveite sua estadia!'},
      {'isBot': false, 'en': 'Gracias. ¡Buen día!', 'pt': 'Eu vou. Bom dia!'},
    ],
  ),
  ChatScenario(
    title: 'Direções e Transporte',
    description: 'Como chegar aos lugares e perguntar por mapas em espanhol.',
    icon: Icons.directions_bus_rounded,
    messages: [
      {'isBot': true, 'en': 'Disculpe, parece un poco perdido. ¿Puedo ayudarle?', 'pt': 'Com licença, você parece um pouco perdido. Posso ajudar?'},
      {'isBot': false, 'en': 'Sí, por favor. ¿Cómo llego a la estación de tren?', 'pt': 'Sim, por favor. Como chego à estação de trem?'},
      {'isBot': true, 'en': 'Está bastante lejos a pie. Debería tomar un autobús.', 'pt': 'É bem longe para ir a pé. Você deveria pegar um ônibus.'},
      {'isBot': false, 'en': '¿Qué número de autobús va allí?', 'pt': 'Qual o número do ônibus que vai pra lá?'},
      {'isBot': true, 'en': 'El autobús número 15 va directo a la estación.', 'pt': 'O ônibus número 15 vai direto para a estação.'},
      {'isBot': false, 'en': '¿Dónde está la parada de autobús más cercana?', 'pt': 'Onde é o ponto de ônibus mais próximo?'},
      {'isBot': true, 'en': 'Siga recto por dos cuadras, luego doble a la derecha.', 'pt': 'Siga reto por dois quarteirões, e então vire à direita.'},
      {'isBot': false, 'en': 'Dos cuadras recto, luego doblar a la derecha. Entendido.', 'pt': 'Dois quarteirões reto, depois virar a direita. Entendido.'},
      {'isBot': true, 'en': 'Exactamente. Está justo frente al supermercado.', 'pt': 'Exatamente. Fica bem na frente do supermercado.'},
      {'isBot': false, 'en': '¿Cuánto cuesta el billete de autobús?', 'pt': 'Quanto é a passagem de ônibus?'},
      {'isBot': true, 'en': 'Cuesta dos dólares y cincuenta centavos.', 'pt': 'Custa dois dólares e cinquenta centavos.'},
      {'isBot': false, 'en': '¿Puedo pagar con tarjeta de crédito en el autobús?', 'pt': 'Eu posso pagar com cartão de crédito no ônibus?'},
      {'isBot': true, 'en': 'Sí, aceptan tarjetas y efectivo.', 'pt': 'Sim, eles aceitam cartões e dinheiro.'},
      {'isBot': false, 'en': '¿Cuánto tiempo dura el viaje?', 'pt': 'Quanto tempo dura a viagem?'},
      {'isBot': true, 'en': 'Tarda unos veinte minutos, dependiendo del tráfico.', 'pt': 'Leva cerca de vinte minutos dependendo do trânsito.'},
      {'isBot': false, 'en': '¿La estación es la última parada?', 'pt': 'A estação é a última parada?'},
      {'isBot': true, 'en': 'No, tiene que bajarse en la quinta parada.', 'pt': 'Não, você tem que descer na quinta parada.'},
      {'isBot': false, 'en': '¡Gracias por su ayuda!', 'pt': 'Obrigado pela sua ajuda!'},
      {'isBot': true, 'en': 'De nada. ¡Buen viaje!', 'pt': 'De nada. Tenha uma jornada segura!'},
      {'isBot': false, 'en': '¡Buen día!', 'pt': 'Tenha um bom dia!'},
    ],
  ),
  ChatScenario(
    title: 'Trabalho e Entrevista',
    description: 'Falando sobre carreira e responder entrevistas em espanhol.',
    icon: Icons.work_rounded,
    messages: [
      {'isBot': true, 'en': 'Buenos días. Por favor, siéntese. Soy el Sr. Miller.', 'pt': 'Bom dia. Por favor, sente-se. Eu sou o Sr. Miller.'},
      {'isBot': false, 'en': 'Buenos días, Sr. Miller. Encantado de conocerle.', 'pt': 'Bom dia, Sr. Miller. Prazer em conhecê-lo.'},
      {'isBot': true, 'en': '¿Puede hablarme un poco sobre usted?', 'pt': 'Pode me falar um pouco sobre você?'},
      {'isBot': false, 'en': 'Claro. Soy un ingeniero de software con experiencia.', 'pt': 'Claro. Sou um engenheiro de software experiente.'},
      {'isBot': true, 'en': '¿Dónde trabajó anteriormente?', 'pt': 'Onde você trabalhava anteriormente?'},
      {'isBot': false, 'en': 'Trabajé en TechCorp durante tres años.', 'pt': 'Eu trabalhei na TechCorp por três anos.'},
      {'isBot': true, 'en': '¿Por qué dejó su último trabajo?', 'pt': 'Por que você saiu do seu último emprego?'},
      {'isBot': false, 'en': 'Estoy buscando un nuevo desafío.', 'pt': 'Estou em busca de um novo desafio.'},
      {'isBot': true, 'en': '¿Cuáles son sus puntos fuertes?', 'pt': 'Quais são as suas maiores qualidades?'},
      {'isBot': false, 'en': 'Aprendo rápido y me gusta trabajar en equipo.', 'pt': 'Eu aprendo rápido e trabalho bem em equipe.'},
      {'isBot': true, 'en': '¿Tiene puntos débiles?', 'pt': 'Você tem algum ponto fraco?'},
      {'isBot': false, 'en': 'A veces me concentro demasiado en los detalles.', 'pt': 'Às vezes, eu me concentro demais nos detalhes.'},
      {'isBot': true, 'en': '¿Se siente cómodo trabajando bajo presión?', 'pt': 'Você fica confortável trabalhando sob pressão?'},
      {'isBot': false, 'en': 'Sí, manejo muy bien la presión.', 'pt': 'Sim, eu lido muito bem com pressão.'},
      {'isBot': true, 'en': '¿Cuáles son sus expectativas salariales?', 'pt': 'Quais são as suas expectativas salariais?'},
      {'isBot': false, 'en': 'Me gustaría hablar de eso después de saber más.', 'pt': 'Eu gostaria de discutir isso após saber mais.'},
      {'isBot': true, 'en': 'Es justo. ¿Tiene alguna pregunta para mí?', 'pt': 'Isso é justo. Você tem alguma pergunta para mim?'},
      {'isBot': false, 'en': 'Sí. ¿Cómo es el equipo?', 'pt': 'Sim. Como é a equipe?'},
      {'isBot': true, 'en': 'Tenemos un equipo muy colaborativo y amable.', 'pt': 'Nós temos uma equipe muito prestativa e amigável.'},
      {'isBot': false, 'en': 'Suena perfecto. Gracias.', 'pt': 'Isso soa perfeito. Obrigado.'},
    ],
  ),
  ChatScenario(
    title: 'No Médico',
    description: 'Como explicar sintomas de forma clara e simples em espanhol.',
    icon: Icons.local_hospital_rounded,
    messages: [
      {'isBot': true, 'en': 'Buenos días. ¿Cuál parece ser el problema hoy?', 'pt': 'Olá. Qual parece ser o problema hoje?'},
      {'isBot': false, 'en': 'Tengo un dolor de cabeza terrible y fiebre.', 'pt': 'Eu tenho uma terrível dor de cabeça e febre.'},
      {'isBot': true, 'en': '¿Desde cuándo se siente así?', 'pt': 'Há quanto tempo você tem se sentido assim?'},
      {'isBot': false, 'en': 'Desde ayer por la mañana.', 'pt': 'Desde ontem de manhã.'},
      {'isBot': true, 'en': '¿Tiene dolor de garganta o tos?', 'pt': 'Você tem dor de garganta ou tosse?'},
      {'isBot': false, 'en': 'Sí, me duele mucho la garganta.', 'pt': 'Sim, minha garganta dói muito.'},
      {'isBot': true, 'en': 'Déjeme comprobar su temperatura. Abra la boca, por favor.', 'pt': 'Deixe-me checar sua temperatura. Abra a boca, por favor.'},
      {'isBot': false, 'en': 'Ahhhh. ¿Está alta?', 'pt': 'Ahhhh. Está alta?'},
      {'isBot': true, 'en': 'Sí, está a 39 grados. Tiene gripe.', 'pt': 'Sim, está 39 graus. Você está com a gripe.'},
      {'isBot': false, 'en': 'Oh no. ¿Qué debo hacer?', 'pt': 'Ah não. O que eu deveria fazer?'},
      {'isBot': true, 'en': 'Debe descansar y beber mucha agua.', 'pt': 'Você precisa descansar e beber bastante água.'},
      {'isBot': false, 'en': '¿Necesito medicamentos?', 'pt': 'Eu preciso de algum remédio?'},
      {'isBot': true, 'en': 'Le voy a recetar analgésicos.', 'pt': 'Eu vou receitar alguns analgésicos para você.'},
      {'isBot': false, 'en': '¿Con qué frecuencia debo tomar el medicamento?', 'pt': 'Com qual frequência eu devo tomar o remédio?'},
      {'isBot': true, 'en': 'Tome una tableta cada ocho horas después de las comidas.', 'pt': 'Tome um comprimido a cada oito horas após as refeições.'},
      {'isBot': false, 'en': '¿Tiene efectos secundarios?', 'pt': 'Existem efeitos colaterais?'},
      {'isBot': true, 'en': 'Podría darle un poco de somnolencia.', 'pt': 'Pode fazer você se sentir um pouco somnolento.'},
      {'isBot': false, 'en': 'Entendido. ¿Debo volver la próxima semana?', 'pt': 'Entendido. Eu devo voltar semana que vem?'},
      {'isBot': true, 'en': 'Vuelva solo si no se siente mejor en tres días.', 'pt': 'Volte apenas se não se sentir melhor em três dias.'},
      {'isBot': false, 'en': 'Gracias, doctor. Buen día.', 'pt': 'Obrigado, doutor. Tenha um bom dia.'},
    ],
  ),
  ChatScenario(
    title: 'Alugando um Carro',
    description: 'Documentos e seguros automotivos essenciais em espanhol.',
    icon: Icons.car_rental_rounded,
    messages: [
      {'isBot': true, 'en': '¡Hola! Bienvenido a Easy Car Rentals.', 'pt': 'Olá! Bem-vindo a Aluguéis de Carros Rápidos.'},
      {'isBot': false, 'en': '¡Hola! Me gustaría alquilar un coche por una semana.', 'pt': 'Oi! Eu gostaria de alugar um carro por uma semana.'},
      {'isBot': true, 'en': 'Claro. ¿Tiene una reserva?', 'pt': 'Claro. Você tem uma reserva?'},
      {'isBot': false, 'en': 'No, no tengo. ¿Tiene coches disponibles?', 'pt': 'Não, eu não tenho. Você tem algum carro disponível?'},
      {'isBot': true, 'en': 'Sí, tenemos un sedán y un coche compacto.', 'pt': 'Sim, nós temos um sedã e um carro compacto.'},
      {'isBot': false, 'en': 'Me llevaré el coche compacto.', 'pt': 'Eu vou ficar com o carro compacto.'},
      {'isBot': true, 'en': 'Excelente. Necesito ver su licencia de conducir y su tarjeta de crédito.', 'pt': 'Ótimo. Eu preciso ver a sua carteira de motorista e o cartão de crédito.'},
      {'isBot': false, 'en': 'Aquí las tiene. ¿Está incluido el seguro?', 'pt': 'Aqui estão. O seguro está incluído?'},
      {'isBot': true, 'en': 'El seguro básico está incluido. ¿Desea cobertura completa?', 'pt': 'O seguro básico está. Gostaria da cobertura completa?'},
      {'isBot': false, 'en': '¿Cuánto cuesta la cobertura completa?', 'pt': 'Quanto custa a cobertura completa?'},
      {'isBot': true, 'en': 'Son quince dólares adicionales por día.', 'pt': 'Custa quinze dólares adicionais por dia.'},
      {'isBot': false, 'en': 'De acuerdo, añadiré la cobertura completa.', 'pt': 'Ok, eu vou adicionar a cobertura completa.'},
      {'isBot': true, 'en': 'El total es de doscientos dólares. ¿Puedo pasar su tarjeta?', 'pt': 'O total é duzentos dólares. Posso passar seu cartão?'},
      {'isBot': false, 'en': 'Sí, adelante.', 'pt': 'Sim, vá em frente.'},
      {'isBot': true, 'en': 'Por favor, firme aquí. El coche está estacionado afuera.', 'pt': 'Por favor, assine aqui. O carro está estacionado lá fora.'},
      {'isBot': false, 'en': '¿Está lleno el tanque de gasolina?', 'pt': 'O tanque de gasolina está cheio?'},
      {'isBot': true, 'en': 'Sí, por favor devuélvalo con el tanque lleno.', 'pt': 'Sim, por favor devolva-o com tanque cheio.'},
      {'isBot': false, 'en': '¿Qué pasa si lo devuelvo tarde?', 'pt': 'O que acontece se eu entregar atrasado?'},
      {'isBot': true, 'en': 'Hay un cargo de diez dólares por cada hora de retraso.', 'pt': 'Há uma taxa de dez dólares por hora de atraso.'},
      {'isBot': false, 'en': 'De acuerdo. Aquí tiene las llaves. ¡Gracias!', 'pt': 'Tudo bem. Aqui estão as chaves. Obrigado!'},
    ],
  ),
  ChatScenario(
    title: 'Hobbies e Entretenimento',
    description: 'Falando sobre fim de semana e o que você gosta em espanhol.',
    icon: Icons.movie_rounded,
    messages: [
      {'isBot': true, 'en': '¡Hola! ¿Cómo estuvo tu fin de semana?', 'pt': 'E aí! Como foi o seu final de semana?'},
      {'isBot': false, 'en': '¡Fue genial! Fui al cine.', 'pt': 'Foi ótimo! Eu fui para o cinema.'},
      {'isBot': true, 'en': '¿De verdad? ¿Qué película viste?', 'pt': 'Sério? Qual filme você assistiu?'},
      {'isBot': false, 'en': 'Vi una nueva película de acción.', 'pt': 'Eu assisti a um novo filme de ação.'},
      {'isBot': true, 'en': '¿Estuvo buena? Me encantan las películas de acción.', 'pt': 'Foi bom? Eu amo filmes de ação.'},
      {'isBot': false, 'en': 'Sí, los efectos especiales fueron increíbles.', 'pt': 'Sim, os efeitos especiais eram incríveis.'},
      {'isBot': true, 'en': '¿Qué más te gusta hacer en tu tiempo libre?', 'pt': 'O que mais você gosta de fazer no tempo livre?'},
      {'isBot': false, 'en': 'Me encanta jugar videojuegos y leer.', 'pt': 'Eu amo jogar video game e ler.'},
      {'isBot': true, 'en': '¡Qué bien! ¿Qué tipo de libros lees?', 'pt': 'Legal! Que tipo de livros você lê?'},
      {'isBot': false, 'en': 'Me gusta leer libros de fantasía y ciencia ficción.', 'pt': 'Eu gosto de ler livros de fantasia e ficção.'},
      {'isBot': true, 'en': 'Prefiero leer biografías. ¿Practicas algún deporte?', 'pt': 'Eu prefiro biografias. Você pratica esportes?'},
      {'isBot': false, 'en': 'Sí, juego al fútbol todos los domingos.', 'pt': 'Sim, eu jogo futebol todo domingo.'},
      {'isBot': true, 'en': '¡El fútbol es muy popular! Yo prefiero correr.', 'pt': 'Futebol é muito popular! Eu prefiro correr.'},
      {'isBot': false, 'en': 'Correr es excelente para la salud.', 'pt': 'Correr é excelente para a saúde.'},
      {'isBot': true, 'en': 'Deberíamos ir al parque este fin de semana.', 'pt': 'Nós deveríamos ir ao parque este fim de semana.'},
      {'isBot': false, 'en': 'Suena como una excelente idea.', 'pt': 'Isso parece uma ótima ideia.'},
      {'isBot': true, 'en': 'Invitemos a nuestros amigos también.', 'pt': 'Vamos convidar nossos amigos também.'},
      {'isBot': false, 'en': 'Los llamaré esta noche.', 'pt': 'Eu ligarei para eles hoje à noite.'},
      {'isBot': true, 'en': 'Genial. No veo la hora de ir.', 'pt': 'Ótimo. Eu estou ansioso por isso.'},
      {'isBot': false, 'en': 'Yo también. ¡Hablamos luego!', 'pt': 'Eu também. Falo com você depois!'},
    ],
  ),
];
