import 'package:flutter/material.dart';

class ChatScenario {
  final String title;
  final String description;
  final IconData icon;
  final List<Map<String, dynamic>> messages;

  ChatScenario({
    required this.title,
    required this.description,
    required this.icon,
    required this.messages,
  });
}

final List<ChatScenario> chatScenarios = [
  ChatScenario(
    title: 'Cumprimentos e Amizade',
    description: 'Aprenda a fazer amigos e manter conversas casuais em francês.',
    icon: Icons.waving_hand_rounded,
    messages: [
      {'isBot': true, 'en': 'Bonjour ! C\'est un plaisir de vous rencontrer.', 'pt': 'Olá! É muito bom conhecer você.'},
      {'isBot': false, 'en': 'Salut ! Ravi de vous rencontrer aussi. Je m\'appelle Alex.', 'pt': 'Oi! Prazer em conhecê-lo também. Meu nome é Alex.'},
      {'isBot': true, 'en': 'D\'où viens-tu, Alex ?', 'pt': 'De onde você é, Alex?'},
      {'isBot': false, 'en': 'Je viens du Brésil. Et toi ?', 'pt': 'Eu sou do Brasil. E você?'},
      {'isBot': true, 'en': 'Je viens des États-Unis. Tu aimes la ville ?', 'pt': 'Eu sou dos Estados Unidos. Você está gostando da cidade?'},
      {'isBot': false, 'en': 'Oui, c\'est très beau ici.', 'pt': 'Sim, é muito bonito aqui.'},
      {'isBot': true, 'en': 'C\'est super. Depuis combien de temps es-tu ici ?', 'pt': 'Isso é ótimo. Há quanto tempo você está aqui?'},
      {'isBot': false, 'en': 'Je suis arrivé il y a trois jours.', 'pt': 'Eu cheguei há três dias atrás.'},
      {'isBot': true, 'en': 'As-tu déjà visité le musée local ?', 'pt': 'Você já visitou o museu local?'},
      {'isBot': false, 'en': 'Pas encore. Est-ce qu\'il est bien ?', 'pt': 'Ainda não. É bom?'},
      {'isBot': true, 'en': 'Oui, la collection d\'art est incroyable.', 'pt': 'Sim, a coleção de arte é incrível.'},
      {'isBot': false, 'en': 'J\'y irai certainement demain.', 'pt': 'Eu com certeza irei lá amanhã.'},
      {'isBot': true, 'en': 'Aimerais-tu de la compagnie ?', 'pt': 'Você gostaria de companhia?'},
      {'isBot': false, 'en': 'Bien sûr, ce serait merveilleux !', 'pt': 'Claro, isso seria maravilhoso!'},
      {'isBot': true, 'en': 'Parfait ! On se retrouve à 10 heures ?', 'pt': 'Perfeito! Vamos nos encontrar às 10 da manhã?'},
      {'isBot': false, 'en': '10 heures du matin, c\'est parfait pour moi.', 'pt': 'Dez da manhã é ótimo para mim.'},
      {'isBot': true, 'en': 'Génial. Laisse-moi te donner mon numéro.', 'pt': 'Incrível. Deixe-me dar o meu número de telefone.'},
      {'isBot': false, 'en': 'Merci. Je t\'appellerai si je me perds.', 'pt': 'Obrigado. Eu te ligo se eu me perder.'},
      {'isBot': true, 'en': 'Ne t\'inquiète pas, c\'est très facile à trouver.', 'pt': 'Não se preocupe, é muito fácil de encontrar.'},
      {'isBot': false, 'en': 'À demain alors. Salut !', 'pt': 'Te vejo amanhã então. Tchau!'},
    ],
  ),
  ChatScenario(
    title: 'No Aeroporto',
    description: 'Conversação prática para check-in e segurança em francês.',
    icon: Icons.flight_takeoff_rounded,
    messages: [
      {'isBot': true, 'en': 'Bonjour. Puis-je voir votre passeport et votre billet, s\'il vous plaît ?', 'pt': 'Bom dia. Posso ver seu passaporte e passagem, por favor?'},
      {'isBot': false, 'en': 'Bonjour. Oui, les voici.', 'pt': 'Bom dia. Sim, aqui estão.'},
      {'isBot': true, 'en': 'Merci. Où voyagez-vous aujourd\'hui ?', 'pt': 'Obrigado. Para onde você está voando hoje?'},
      {'isBot': false, 'en': 'Je voyage à New York.', 'pt': 'Estou voando para Nova Iorque.'},
      {'isBot': true, 'en': 'Enregistrez-vous des bagages ?', 'pt': 'Você vai despachar alguma mala?'},
      {'isBot': false, 'en': 'Oui, j\'ai une valise.', 'pt': 'Sim, eu tenho uma mala.'},
      {'isBot': true, 'en': 'S\'il vous plaît, placez-la sur la balance.', 'pt': 'Por favor, coloque-a na balança.'},
      {'isBot': false, 'en': 'Bien sûr. Est-ce qu\'elle dépasse le poids limite ?', 'pt': 'Claro. Está com excesso de peso?'},
      {'isBot': true, 'en': 'Non, c\'est parfait. Vous préférez un siège côté couloir ou côté fenêtre ?', 'pt': 'Não, está perfeitamente bem. Gostaria de assento no corredor ou janela?'},
      {'isBot': false, 'en': 'Côté fenêtre, s\'il vous plaît.', 'pt': 'Um assento na janela, por favor.'},
      {'isBot': true, 'en': 'Très bien. Voici votre carte d\'embarquement.', 'pt': 'Certo. Aqui está seu cartão de embarque.'},
      {'isBot': false, 'en': 'Merci. C\'est quelle porte ?', 'pt': 'Obrigado. Qual é o portão?'},
      {'isBot': true, 'en': 'Votre porte est la B12. L\'embarquement commence à 14 heures.', 'pt': 'Seu portão é o B12. O embarque começa às 2 da tarde.'},
      {'isBot': false, 'en': 'Et où se trouve le contrôle de sécurité ?', 'pt': 'E onde é a verificação de segurança?'},
      {'isBot': true, 'en': 'La sécurité est juste au coin à votre gauche.', 'pt': 'A segurança fica virando a esquina à sua esquerda.'},
      {'isBot': false, 'en': 'Dois-je enlever mes chaussures ?', 'pt': 'Preciso tirar meus sapatos?'},
      {'isBot': true, 'en': 'Oui, veuillez retirer vos chaussures et vos vestes.', 'pt': 'Sim, por favor remova seus sapatos e jaquetas.'},
      {'isBot': false, 'en': 'D\'accord, je vais faire ça.', 'pt': 'Certo, farei isso.'},
      {'isBot': true, 'en': 'Bon vol !', 'pt': 'Tenha um voo seguro!'},
      {'isBot': false, 'en': 'Merci ! Bonne journée.', 'pt': 'Obrigado! Tenha um bom dia.'},
    ],
  ),
  ChatScenario(
    title: 'No Restaurante',
    description: 'Do pedido da comida até o momento de pagar a conta em francês.',
    icon: Icons.restaurant_rounded,
    messages: [
      {'isBot': true, 'en': 'Bienvenue ! Une table pour une personne ?', 'pt': 'Bem-vindo! Uma mesa para um?'},
      {'isBot': false, 'en': 'Oui, s\'il vous plaît. Près de la fenêtre si possible.', 'pt': 'Sim, por favor. Perto da janela, se possível.'},
      {'isBot': true, 'en': 'Par ici. Voici votre menu.', 'pt': 'Por aqui. Aqui está o seu menu.'},
      {'isBot': false, 'en': 'Merci. Puis-je avoir un verre d\'eau ?', 'pt': 'Obrigado(a). Posso tomar um copo de água?'},
      {'isBot': true, 'en': 'Bien sûr. Êtes-vous prêt à commander maintenant ?', 'pt': 'Claro. Você está pronto para fazer o pedido agora?'},
      {'isBot': false, 'en': 'J\'ai besoin de quelques minutes de plus, s\'il vous plaît.', 'pt': 'Preciso de mais alguns minutos, por favor.'},
      {'isBot': true, 'en': 'Prenez votre temps. Faites-moi savoir quand vous serez prêt.', 'pt': 'Fique à vontade. Me avise quando estiver pronto.'},
      {'isBot': false, 'en': 'D\'accord. Je suis prêt à commander.', 'pt': 'Certo. Estou pronto para pedir.'},
      {'isBot': true, 'en': 'Que aimeriez-vous manger aujourd\'hui ?', 'pt': 'O que você gostaria hoje?'},
      {'isBot': false, 'en': 'Je vais prendre le poulet grillé avec de la salade.', 'pt': 'Eu vou querer o frango grelhado com salada.'},
      {'isBot': true, 'en': 'Excellent choix. Une sauce pour la salade ?', 'pt': 'Excelente escolha. Algum molho para a salada?'},
      {'isBot': false, 'en': 'Juste de l\'huile d\'olive et du citron, merci.', 'pt': 'Apenas azeite e limão, obrigado(a).'},
      {'isBot': true, 'en': 'Et aimeriez-vous quelque chose à boire ?', 'pt': 'E gostaria de algo para beber?'},
      {'isBot': false, 'en': 'Un verre de jus d\'orange, s\'il vous plaît.', 'pt': 'Um copo de suco de laranja, por favor.'},
      {'isBot': true, 'en': 'Votre repas sera prêt dans 15 minutes.', 'pt': 'Sua comida estará pronta em 15 minutos.'},
      {'isBot': false, 'en': 'Parfait, j\'ai très faim.', 'pt': 'Perfeito, estou com muita fome.'},
      {'isBot': true, 'en': 'Voici votre repas. Bon appétit !', 'pt': 'Aqui está sua refeição. Aproveite!'},
      {'isBot': false, 'en': 'Ça a l\'air délicieux. Puis-je avoir l\'addition, s\'il vous plaît ?', 'pt': 'Parece delicioso. Pode me trazer a conta, por favor?'},
      {'isBot': true, 'en': 'Bien sûr. Comment souhaitez-vous payer ?', 'pt': 'Certamente. Como você gostaria de pagar?'},
      {'isBot': false, 'en': 'Je vais payer par carte de crédit.', 'pt': 'Eu pagarei com cartão de crédito.'},
    ],
  ),
  ChatScenario(
    title: 'Compras e Lojas',
    description: 'Aprenda expressões para provar e comprar produtos em francês.',
    icon: Icons.shopping_bag_rounded,
    messages: [
      {'isBot': true, 'en': 'Bonjour ! Puis-je vous aider à trouver quelque chose ?', 'pt': 'Olá! Posso ajudar você a encontrar algo?'},
      {'isBot': false, 'en': 'Oui, je cherche un manteau d\'hiver.', 'pt': 'Sim, estou procurando um casaco de inverno.'},
      {'isBot': true, 'en': 'Nos manteaux d\'hiver sont juste ici. Quelle taille ?', 'pt': 'Nossos casacos de inverno estão bem aqui. Qual tamanho?'},
      {'isBot': false, 'en': 'Je porte habituellement du M.', 'pt': 'Eu costumo usar médio.'},
      {'isBot': true, 'en': 'En voici un joli bleu en taille M. Essayez-le.', 'pt': 'Aqui tem um azul bonito no tamanho médio. Experimente.'},
      {'isBot': false, 'en': 'Où sont les cabines d\'essayage ?', 'pt': 'Onde ficam os provadores?'},
      {'isBot': true, 'en': 'Elles sont au fond du magasin, à gauche.', 'pt': 'Ficam no fundo da loja, à esquerda.'},
      {'isBot': false, 'en': 'Merci. Je vais aller l\'essayer.', 'pt': 'Obrigado. Eu vou experimentar.'},
      {'isBot': true, 'en': 'Comment ça va ?', 'pt': 'Como serviu?'},
      {'isBot': false, 'en': 'C\'est un peu trop serré. Avez-vous une taille L ?', 'pt': 'Ficou um pouco apertado. Você tem um grande?'},
      {'isBot': true, 'en': 'Laissez-moi vérifier... Oui, en voici un en taille L.', 'pt': 'Deixe-me checar... Sim, aqui está um tamanho grande.'},
      {'isBot': false, 'en': 'Celui-ci va parfaitement. C\'est combien ?', 'pt': 'Esse serviu perfeitamente. Quanto custa?'},
      {'isBot': true, 'en': 'C\'est cinquante-cinq dollars.', 'pt': 'Custa cinquenta e cinco dólares.'},
      {'isBot': false, 'en': 'Avez-vous des réductions aujourd\'hui ?', 'pt': 'Vocês têm algum desconto hoje?'},
      {'isBot': true, 'en': 'Oui, il y a une réduction de 10% sur tous les vêtements d\'hiver.', 'pt': 'Sim, tem um desconto de 10% em todas roupas de inverno.'},
      {'isBot': false, 'en': 'C\'est super. Je le prends.', 'pt': 'Isso é ótimo. Eu vou levar.'},
      {'isBot': true, 'en': 'Souhaitez-vous payer en espèces ou par carte ?', 'pt': 'Gostaria de pagar com dinheiro ou cartão?'},
      {'isBot': false, 'en': 'Je vais payer en espèces. Voici soixante dollars.', 'pt': 'Pagarei em dinheiro. Aqui estão sessenta dólares.'},
      {'isBot': true, 'en': 'Voici votre monnaie et votre reçu. Bonne journée !', 'pt': 'Aqui está seu troco e sua nota fiscal. Tenha um bom dia!'},
      {'isBot': false, 'en': 'Merci beaucoup. Au revoir.', 'pt': 'Muito obrigado. Tchau.'},
    ],
  ),
  ChatScenario(
    title: 'Na Recepção do Hotel',
    description: 'Reservas, check-in e pedidos especiais em francês.',
    icon: Icons.hotel_rounded,
    messages: [
      {'isBot': true, 'en': 'Bienvenue au Grand Hôtel. Comment puis-je vous aider ?', 'pt': 'Bem-vindo ao Grand Hotel. Como posso ajudá-lo?'},
      {'isBot': false, 'en': 'J\'ai une réservation au nom de John Smith.', 'pt': 'Eu tenho uma reserva no nome de John Smith.'},
      {'isBot': true, 'en': 'Laissez-moi vérifier... Ah oui, une chambre simple pour trois nuits. Est-ce correct ?', 'pt': 'Deixe-me checar... Ah sim, um quarto de solteiro por três noites.'},
      {'isBot': false, 'en': 'C\'est correct. Le petit-déjeuner est-il inclus ?', 'pt': 'Isso está correto. O café da manhã está incluído?'},
      {'isBot': true, 'en': 'Oui, le petit-déjeuner est servi de 7h à 10h.', 'pt': 'Sim, o café da manhã é servido das 7 às 10 da manhã.'},
      {'isBot': false, 'en': 'Super. À quel étage se trouve ma chambre ?', 'pt': 'Ótimo. Em qual andar fica o meu quarto?'},
      {'isBot': true, 'en': 'Vous êtes au cinquième étage, chambre 502.', 'pt': 'Você está no quinto andar, quarto 502.'},
      {'isBot': false, 'en': 'Y a-t-il le Wi-Fi gratuit dans la chambre ?', 'pt': 'Vocês têm Wi-Fi grátis no quarto?'},
      {'isBot': true, 'en': 'Oui, le mot de passe est écrit sur votre carte-clé.', 'pt': 'Sim, a senha está escrita no seu cartão-chave.'},
      {'isBot': false, 'en': 'Y a-t-il une salle de sport dans l\'hôtel ?', 'pt': 'Tem academia no hotel?'},
      {'isBot': true, 'en': 'Oui, la salle de sport est au rez-de-chaussée à côté de la piscine.', 'pt': 'Sim, a academia fica no térreo ao lado da piscina.'},
      {'isBot': false, 'en': 'Puis-je demander un réveil par téléphone pour demain ?', 'pt': 'Posso pedir uma ligação de despertar para amanhã?'},
      {'isBot': true, 'en': 'Bien sûr. À quelle heure souhaitez-vous vous réveiller ?', 'pt': 'Claro. A que horas gostaria de acordar?'},
      {'isBot': false, 'en': 'À six heures et demie du matin, s\'il vous plaît.', 'pt': 'Às seis e meia da manhã, por favor.'},
      {'isBot': true, 'en': 'C\'est noté. Avez-vous besoin d\'aide pour vos bagages ?', 'pt': 'Anotado. Precisa de ajuda com as malas?'},
      {'isBot': false, 'en': 'Non merci, je peux me débrouiller. Où est l\'ascenseur ?', 'pt': 'Não obrigado, eu dou conta. Onde é o elevador?'},
      {'isBot': true, 'en': 'Les ascenseurs sont juste derrière vous.', 'pt': 'Os elevadores estão bem atrás de você.'},
      {'isBot': false, 'en': 'Merci ! À quelle heure est le départ ?', 'pt': 'Obrigado! A que horas é o checkout?'},
      {'isBot': true, 'en': 'Le départ est à 11h. Bon séjour !', 'pt': 'O checkout é às 11 da manhã. Aproveite sua estadia!'},
      {'isBot': false, 'en': 'Merci. Bonne journée !', 'pt': 'Eu vou. Bom dia!'},
    ],
  ),
  ChatScenario(
    title: 'Direções e Transporte',
    description: 'Como chegar aos lugares e perguntar por mapas em francês.',
    icon: Icons.directions_bus_rounded,
    messages: [
      {'isBot': true, 'en': 'Excusez-moi, vous avez l\'air un peu perdu. Puis-je vous aider ?', 'pt': 'Com licença, você parece um pouco perdido. Posso ajudar?'},
      {'isBot': false, 'en': 'Oui, s\'il vous plaît. Comment puis-je aller à la gare ?', 'pt': 'Sim, por favor. Como chego à estação de trem?'},
      {'isBot': true, 'en': 'C\'est assez loin à pied. Vous devriez prendre un bus.', 'pt': 'É bem longe para ir a pé. Você deveria pegar um ônibus.'},
      {'isBot': false, 'en': 'Quel numéro de bus y va ?', 'pt': 'Qual o número do ônibus que vai pra lá?'},
      {'isBot': true, 'en': 'Le bus numéro 15 va directement à la gare.', 'pt': 'O ônibus número 15 vai direto para a estação.'},
      {'isBot': false, 'en': 'Où se trouve l\'arrêt de bus le plus proche ?', 'pt': 'Onde é o ponto de ônibus mais próximo?'},
      {'isBot': true, 'en': 'Allez tout droit pendant deux pâtés de maisons, puis tournez à droite.', 'pt': 'Siga reto por dois quarteirões, e então vire à direita.'},
      {'isBot': false, 'en': 'Deux blocs tout droit, puis tourner à droite. Compris.', 'pt': 'Dois quarteirões reto, depois virar a direita. Entendido.'},
      {'isBot': true, 'en': 'Exactement. C\'est juste devant le supermarché.', 'pt': 'Exatamente. Fica bem na frente do supermercado.'},
      {'isBot': false, 'en': 'C\'est combien le ticket de bus ?', 'pt': 'Quanto é a passagem de ônibus?'},
      {'isBot': true, 'en': 'Ça coûte deux dollars et cinquante cents.', 'pt': 'Custa dois dólares e cinquenta centavos.'},
      {'isBot': false, 'en': 'Puis-je payer par carte de crédit dans le bus ?', 'pt': 'Eu posso pagar com cartão de crédito no ônibus?'},
      {'isBot': true, 'en': 'Oui, ils acceptent les cartes et les espèces.', 'pt': 'Sim, eles aceitam cartões e dinheiro.'},
      {'isBot': false, 'en': 'Combien de temps dure le trajet ?', 'pt': 'Quanto tempo dura a viagem?'},
      {'isBot': true, 'en': 'Ça prend environ vingt minutes selon le trafic.', 'pt': 'Leva cerca de vinte minutos dependendo do trânsito.'},
      {'isBot': false, 'en': 'La gare est-elle le dernier arrêt ?', 'pt': 'A estação é a última parada?'},
      {'isBot': true, 'en': 'Non, vous devez descendre au cinquième arrêt.', 'pt': 'Não, você tem que descer na quinta parada.'},
      {'isBot': false, 'en': 'Merci pour votre aide !', 'pt': 'Obrigado pela sua ajuda!'},
      {'isBot': true, 'en': 'De rien. Bon voyage !', 'pt': 'De nada. Tenha uma jornada segura!'},
      {'isBot': false, 'en': 'Bonne journée !', 'pt': 'Tenha um bom dia!'},
    ],
  ),
  ChatScenario(
    title: 'Trabalho e Entrevista',
    description: 'Falando sobre carreira e responder entrevistas em francês.',
    icon: Icons.work_rounded,
    messages: [
      {'isBot': true, 'en': 'Bonjour. Veuillez vous asseoir. Je suis M. Miller.', 'pt': 'Bom dia. Por favor, sente-se. Eu sou o Sr. Miller.'},
      {'isBot': false, 'en': 'Bonjour, M. Miller. Ravi de vous rencontrer.', 'pt': 'Bom dia, Sr. Miller. Prazer em conhecê-lo.'},
      {'isBot': true, 'en': 'Pouvez-vous me parler un peu de vous ?', 'pt': 'Pode me falar um pouco sobre você?'},
      {'isBot': false, 'en': 'Bien sûr. Je suis un ingénieur logiciel expérimenté.', 'pt': 'Claro. Sou um engenheiro de software experiente.'},
      {'isBot': true, 'en': 'Où avez-vous travaillé auparavant ?', 'pt': 'Onde você trabalhava anteriormente?'},
      {'isBot': false, 'en': 'J\'ai travaillé chez TechCorp pendant trois ans.', 'pt': 'Eu trabalhei na TechCorp por três anos.'},
      {'isBot': true, 'en': 'Pourquoi avez-vous quitté votre dernier emploi ?', 'pt': 'Por que você saiu do seu último emprego?'},
      {'isBot': false, 'en': 'Je cherche un nouveau défi.', 'pt': 'Estou em busca de um novo desafio.'},
      {'isBot': true, 'en': 'Quels sont vos points forts ?', 'pt': 'Quais são as suas maiores qualidades?'},
      {'isBot': false, 'en': 'J\'apprends vite et j\'aime le travail d\'équipe.', 'pt': 'Eu aprendo rápido e trabalho bem em equipe.'},
      {'isBot': true, 'en': 'Avez-vous des points faibles ?', 'pt': 'Você tem algum ponto fraco?'},
      {'isBot': false, 'en': 'Parfois, je me concentre trop sur les détails.', 'pt': 'Às vezes, eu me concentro demais nos detalhes.'},
      {'isBot': true, 'en': 'Êtes-vous à l\'aise pour travailler sous pression ?', 'pt': 'Você fica confortável trabalhando sob pressão?'},
      {'isBot': false, 'en': 'Oui, je gère très bien la pression.', 'pt': 'Sim, eu lido muito bem com pressão.'},
      {'isBot': true, 'en': 'Quelles sont vos attentes salariales ?', 'pt': 'Quais são as suas expectativas salariais?'},
      {'isBot': false, 'en': 'J\'aimerais en discuter après en savoir plus.', 'pt': 'Eu gostaria de discutir isso após saber mais.'},
      {'isBot': true, 'en': 'C\'est juste. Avez-vous des questions pour moi ?', 'pt': 'Isso é justo. Você tem alguma pergunta para mim?'},
      {'isBot': false, 'en': 'Oui. Comment est l\'équipe ?', 'pt': 'Sim. Como é a equipe?'},
      {'isBot': true, 'en': 'Nous avons une équipe très collaborative et amicale.', 'pt': 'Nós temos uma equipe muito prestativa e amigável.'},
      {'isBot': false, 'en': 'Ça a l\'air parfait. Merci.', 'pt': 'Isso soa perfeito. Obrigado.'},
    ],
  ),
  ChatScenario(
    title: 'No Médico',
    description: 'Como explicar sintomas de forma clara e simples em francês.',
    icon: Icons.local_hospital_rounded,
    messages: [
      {'isBot': true, 'en': 'Bonjour. Quel semble être le problème aujourd\'hui ?', 'pt': 'Olá. Qual parece ser o problema hoje?'},
      {'isBot': false, 'en': 'J\'ai un terrible mal de tête et de la fièvre.', 'pt': 'Eu tenho uma terrível dor de cabeça e febre.'},
      {'isBot': true, 'en': 'Depuis combien de temps vous sentez-vous comme ça ?', 'pt': 'Há quanto tempo você tem se sentido assim?'},
      {'isBot': false, 'en': 'Depuis hier matin.', 'pt': 'Desde ontem de manhã.'},
      {'isBot': true, 'en': 'Avez-vous mal à la gorge ou de la toux ?', 'pt': 'Você tem dor de garganta ou tosse?'},
      {'isBot': false, 'en': 'Oui, ma gorge fait très mal.', 'pt': 'Sim, minha garganta dói muito.'},
      {'isBot': true, 'en': 'Laissez-moi vérifier votre température. Ouvrez la bouche, s\'il vous plaît.', 'pt': 'Deixe-me checar sua temperatura. Abra a boca, por favor.'},
      {'isBot': false, 'en': 'Ahhhh. Est-elle élevée ?', 'pt': 'Ahhhh. Está alta?'},
      {'isBot': true, 'en': 'Oui, elle est de 39 degrés. Vous avez la grippe.', 'pt': 'Sim, está 39 graus. Você está com a gripe.'},
      {'isBot': false, 'en': 'Oh no. Que dois-je faire ?', 'pt': 'Ah não. O que eu deveria fazer?'},
      {'isBot': true, 'en': 'Vous devez vous reposer et boire beaucoup d\'eau.', 'pt': 'Você precisa descansar e beber bastante água.'},
      {'isBot': false, 'en': 'Ai-je besoin de médicaments ?', 'pt': 'Eu preciso de algum remédio?'},
      {'isBot': true, 'en': 'Je vais vous prescrire des analgésiques.', 'pt': 'Eu vou receitar alguns analgésicos para você.'},
      {'isBot': false, 'en': 'À quelle fréquence dois-je prendre le médicament ?', 'pt': 'Com qual frequência eu devo tomar o remédio?'},
      {'isBot': true, 'en': 'Prenez un comprimé toutes les huit heures après les repas.', 'pt': 'Tome um comprimido a cada oito horas após as refeições.'},
      {'isBot': false, 'en': 'Y a-t-il des effets secondaires ?', 'pt': 'Existem efeitos colaterais?'},
      {'isBot': true, 'en': 'Cela pourrait vous rendre un peu somnolent.', 'pt': 'Pode fazer você se sentir um pouco sonolento.'},
      {'isBot': false, 'en': 'Compris. Dois-je revenir la semaine prochaine ?', 'pt': 'Entendido. Eu devo voltar semana que vem?'},
      {'isBot': true, 'en': 'Revenez seulement si vous ne vous sentez pas mieux dans trois jours.', 'pt': 'Volte apenas se não se sentir melhor em três dias.'},
      {'isBot': false, 'en': 'Merci, docteur. Bonne journée.', 'pt': 'Obrigado, doutor. Tenha um bom dia.'},
    ],
  ),
  ChatScenario(
    title: 'Alugando um Carro',
    description: 'Documentos e seguros automotivos essenciais em francês.',
    icon: Icons.car_rental_rounded,
    messages: [
      {'isBot': true, 'en': 'Bonjour ! Bienvenue chez Easy Car Rentals.', 'pt': 'Olá! Bem-vindo a Aluguéis de Carros Rápidos.'},
      {'isBot': false, 'en': 'Bonjour ! Je voudrais louer une voiture pour une semaine.', 'pt': 'Oi! Eu gostaria de alugar um carro por uma semana.'},
      {'isBot': true, 'en': 'Bien sûr. Avez-vous une réservation ?', 'pt': 'Claro. Você tem uma reserva?'},
      {'isBot': false, 'en': 'Non, je n\'en ai pas. Avez-vous des voitures disponibles ?', 'pt': 'Não, eu não tenho. Você tem algum carro disponível?'},
      {'isBot': true, 'en': 'Oui, nous avons une berline et une voiture compacte.', 'pt': 'Sim, nós temos um sedã e um carro compacto.'},
      {'isBot': false, 'en': 'Je vais prendre la voiture compacte.', 'pt': 'Eu vou ficar com o carro compacto.'},
      {'isBot': true, 'en': 'Super. J\'ai besoin de voir votre permis de conduire et votre carte de crédit.', 'pt': 'Ótimo. Eu preciso ver a sua carteira de motorista e o cartão de crédito.'},
      {'isBot': false, 'en': 'Les voici. L\'assurance est-elle incluse ?', 'pt': 'Aqui estão. O seguro está incluído?'},
      {'isBot': true, 'en': 'L\'assurance de base est incluse. Souhaitez-vous une couverture complète ?', 'pt': 'O seguro básico está. Gostaria da cobertura completa?'},
      {'isBot': false, 'en': 'Combien coûte la couverture complète ?', 'pt': 'Quanto custa a cobertura completa?'},
      {'isBot': true, 'en': 'C\'est quinze dollars de plus par jour.', 'pt': 'Custa quinze dólares adicionais por dia.'},
      {'isBot': false, 'en': 'D\'accord, je vais ajouter la couverture complète.', 'pt': 'Ok, eu vou adicionar a cobertura completa.'},
      {'isBot': true, 'en': 'Le total est de deux cents dollars. Puis-je passer votre carte ?', 'pt': 'O total é duzentos dólares. Posso passar seu cartão?'},
      {'isBot': false, 'en': 'Oui, allez-y.', 'pt': 'Sim, vá em frente.'},
      {'isBot': true, 'en': 'Veuillez signer ici. La voiture est garée dehors.', 'pt': 'Por favor, assine aqui. O carro está estacionado lá fora.'},
      {'isBot': false, 'en': 'Le réservoir d\'essence est-il plein ?', 'pt': 'O tanque de gasolina está cheio?'},
      {'isBot': true, 'en': 'Oui, veuillez la retourner avec le réservoir plein.', 'pt': 'Sim, por favor devolva-o com tanque cheio.'},
      {'isBot': false, 'en': 'Qu\'est-ce qui se passe si je la rends en retard ?', 'pt': 'O que acontece se eu entregar atrasado?'},
      {'isBot': true, 'en': 'Il y a des frais de dix dollars par heure de retard.', 'pt': 'Há uma taxa de dez dólares por hora de atraso.'},
      {'isBot': false, 'en': 'D\'accord. Voici les clés. Merci !', 'pt': 'Tudo bem. Aqui estão as chaves. Obrigado!'},
    ],
  ),
  ChatScenario(
    title: 'Hobbies e Entretenimento',
    description: 'Falando sobre fim de semana e o que você gosta em francês.',
    icon: Icons.movie_rounded,
    messages: [
      {'isBot': true, 'en': 'Salut ! Comment s\'est passé ton week-end ?', 'pt': 'E aí! Como foi o seu final de semana?'},
      {'isBot': false, 'en': 'C\'est super ! Je suis allé au cinéma.', 'pt': 'Foi ótimo! Eu fui para o cinema.'},
      {'isBot': true, 'en': 'Vraiment ? Quel film as-tu regardé ?', 'pt': 'Sério? Qual filme você assistiu?'},
      {'isBot': false, 'en': 'J\'ai regardé un nouveau film d\'action.', 'pt': 'Eu assisti a um novo filme de ação.'},
      {'isBot': true, 'en': 'C\'était bien ? J\'adore les films d\'action.', 'pt': 'Foi bom? Eu amo filmes de ação.'},
      {'isBot': false, 'en': 'Oui, les effets spéciaux étaient incroyables.', 'pt': 'Sim, os efeitos especiais eram incríveis.'},
      {'isBot': true, 'en': 'Qu\'est-ce que tu aimes faire d\'autre pendant ton temps libre ?', 'pt': 'O que mais você gosta de fazer no tempo livre?'},
      {'isBot': false, 'en': 'J\'adore jouer aux jeux vidéo et lire.', 'pt': 'Eu amo jogar video game e ler.'},
      {'isBot': true, 'en': 'Cool ! Quel genre de livres lis-tu ?', 'pt': 'Legal! Que tipo de livros você lê?'},
      {'isBot': false, 'en': 'J\'aime lire des livres de fantasy et de science-fiction.', 'pt': 'Eu gosto de ler livros de fantasia e ficção.'},
      {'isBot': true, 'en': 'Je préfère lire des biographies. Tu fais du sport ?', 'pt': 'Eu prefiro biografias. Você pratica esportes?'},
      {'isBot': false, 'en': 'Oui, je joue au football tous les dimanches.', 'pt': 'Sim, eu jogo futebol todo domingo.'},
      {'isBot': true, 'en': 'Le football est très populaire ! Je préfère courir.', 'pt': 'Futebol é muito popular! Eu prefiro correr.'},
      {'isBot': false, 'en': 'Courir est excellent pour la santé.', 'pt': 'Correr é excelente para a saúde.'},
      {'isBot': true, 'en': 'Nous devrions aller au parc ce week-end.', 'pt': 'Nós deveríamos ir ao parque este fim de semana.'},
      {'isBot': false, 'en': 'Ça a l\'air d\'être une excellente idée.', 'pt': 'Isso parece uma ótima ideia.'},
      {'isBot': true, 'en': 'Invitons aussi nos amis.', 'pt': 'Vamos convidar nossos amigos também.'},
      {'isBot': false, 'en': 'Je les appellerai ce soir.', 'pt': 'Eu ligarei para eles hoje à noite.'},
      {'isBot': true, 'en': 'Super. J\'ai hâte d\'y être.', 'pt': 'Ótimo. Eu estou ansioso por isso.'},
      {'isBot': false, 'en': 'Moi aussi. On se parle plus tard !', 'pt': 'Eu também. Falo com você depois!'},
    ],
  ),
];
