import 'package:flutter/material.dart';

class ChatScenario {
  final String title;
  final String description;
  final IconData icon;
  final List<Map<String, dynamic>> messages;

  ChatScenario({
    required this.title,
    required this.description,
    required this.icon,
    required this.messages,
  });
}

final List<ChatScenario> chatScenarios = [
  ChatScenario(
    title: 'Cumprimentos e Amizade',
    description: 'Aprenda a fazer amigos e manter conversas casuais.',
    icon: Icons.waving_hand_rounded,
    messages: [
      {'isBot': true, 'en': 'Hello! It is so nice to meet you.', 'pt': 'Olá! É muito bom conhecer você.'},
      {'isBot': false, 'en': 'Hi! Nice to meet you too. My name is Alex.', 'pt': 'Oi! Prazer em conhecê-lo também. Meu nome é Alex.'},
      {'isBot': true, 'en': 'Where are you from, Alex?', 'pt': 'De onde você é, Alex?'},
      {'isBot': false, 'en': 'I am from Brazil. And you?', 'pt': 'Eu sou do Brasil. E você?'},
      {'isBot': true, 'en': 'I am from the United States. Are you enjoying the city?', 'pt': 'Eu sou dos Estados Unidos. Você está gostando da cidade?'},
      {'isBot': false, 'en': 'Yes, it is very beautiful here.', 'pt': 'Sim, é muito bonito aqui.'},
      {'isBot': true, 'en': 'That is great. How long have you been here?', 'pt': 'Isso é ótimo. Há quanto tempo você está aqui?'},
      {'isBot': false, 'en': 'I arrived three days ago.', 'pt': 'Eu cheguei há três dias atrás.'},
      {'isBot': true, 'en': 'Have you visited the local museum yet?', 'pt': 'Você já visitou o museu local?'},
      {'isBot': false, 'en': 'Not yet. Is it good?', 'pt': 'Ainda não. É bom?'},
      {'isBot': true, 'en': 'Yes, the art collection is amazing.', 'pt': 'Sim, a coleção de arte é incrível.'},
      {'isBot': false, 'en': 'I will definitely go there tomorrow.', 'pt': 'Eu com certeza irei lá amanhã.'},
      {'isBot': true, 'en': 'Would you like some company?', 'pt': 'Você gostaria de companhia?'},
      {'isBot': false, 'en': 'Sure, that would be wonderful!', 'pt': 'Claro, isso seria maravilhoso!'},
      {'isBot': true, 'en': 'Perfect! Shall we meet at 10 AM?', 'pt': 'Perfeito! Vamos nos encontrar às 10 da manhã?'},
      {'isBot': false, 'en': 'Ten AM is great for me.', 'pt': 'Dez da manhã é ótimo para mim.'},
      {'isBot': true, 'en': 'Awesome. Let me give you my phone number.', 'pt': 'Incrível. Deixe-me dar o meu número de telefone.'},
      {'isBot': false, 'en': 'Thanks. I will call you if I get lost.', 'pt': 'Obrigado. Eu te ligo se eu me perder.'},
      {'isBot': true, 'en': 'Do not worry, it is very easy to find.', 'pt': 'Não se preocupe, é muito fácil de encontrar.'},
      {'isBot': false, 'en': 'See you tomorrow then. Bye!', 'pt': 'Te vejo amanhã então. Tchau!'},
    ],
  ),
  ChatScenario(
    title: 'No Aeroporto',
    description: 'Conversação prática para check-in e segurança.',
    icon: Icons.flight_takeoff_rounded,
    messages: [
      {'isBot': true, 'en': 'Good morning. Can I see your passport and ticket, please?', 'pt': 'Bom dia. Posso ver seu passaporte e passagem, por favor?'},
      {'isBot': false, 'en': 'Good morning. Yes, here they are.', 'pt': 'Bom dia. Sim, aqui estão.'},
      {'isBot': true, 'en': 'Thank you. Where are you flying to today?', 'pt': 'Obrigado. Para onde você está voando hoje?'},
      {'isBot': false, 'en': 'I am flying to New York.', 'pt': 'Estou voando para Nova Iorque.'},
      {'isBot': true, 'en': 'Are you checking any bags?', 'pt': 'Você vai despachar alguma mala?'},
      {'isBot': false, 'en': 'Yes, I have one suitcase.', 'pt': 'Sim, eu tenho uma mala.'},
      {'isBot': true, 'en': 'Please place it on the scale.', 'pt': 'Por favor, coloque-a na balança.'},
      {'isBot': false, 'en': 'Sure. Is it overweight?', 'pt': 'Claro. Está com excesso de peso?'},
      {'isBot': true, 'en': 'No, it is perfectly fine. Would you like an aisle or window seat?', 'pt': 'Não, está perfeitamente bem. Gostaria de assento no corredor ou janela?'},
      {'isBot': false, 'en': 'A window seat, please.', 'pt': 'Um assento na janela, por favor.'},
      {'isBot': true, 'en': 'Alright. Here is your boarding pass.', 'pt': 'Certo. Aqui está seu cartão de embarque.'},
      {'isBot': false, 'en': 'Thank you. Which gate is it?', 'pt': 'Obrigado. Qual é o portão?'},
      {'isBot': true, 'en': 'Your gate is B12. Boarding starts at 2 PM.', 'pt': 'Seu portão é o B12. O embarque começa às 2 da tarde.'},
      {'isBot': false, 'en': 'And where is the security check?', 'pt': 'E onde é a verificação de segurança?'},
      {'isBot': true, 'en': 'Security is just around the corner to your left.', 'pt': 'A segurança fica virando a esquina à sua esquerda.'},
      {'isBot': false, 'en': 'Do I need to take off my shoes?', 'pt': 'Preciso tirar meus sapatos?'},
      {'isBot': true, 'en': 'Yes, please remove your shoes and jackets.', 'pt': 'Sim, por favor remova seus sapatos e jaquetas.'},
      {'isBot': false, 'en': 'Okay, I will do that.', 'pt': 'Certo, farei isso.'},
      {'isBot': true, 'en': 'Have a safe flight!', 'pt': 'Tenha um voo seguro!'},
      {'isBot': false, 'en': 'Thanks! Have a good day.', 'pt': 'Obrigado! Tenha um bom dia.'},
    ],
  ),
  ChatScenario(
    title: 'No Restaurante',
    description: 'Do pedido da comida até o momento de pagar a conta.',
    icon: Icons.restaurant_rounded,
    messages: [
      {'isBot': true, 'en': 'Welcome! A table for one?', 'pt': 'Bem-vindo! Uma mesa para um?'},
      {'isBot': false, 'en': 'Yes, please. By the window if possible.', 'pt': 'Sim, por favor. Perto da janela, se possível.'},
      {'isBot': true, 'en': 'Right this way. Here is your menu.', 'pt': 'Por aqui. Aqui está o seu menu.'},
      {'isBot': false, 'en': 'Thank you. Can I get a glass of water?', 'pt': 'Obrigado(a). Posso tomar um copo de água?'},
      {'isBot': true, 'en': 'Of course. Are you ready to order now?', 'pt': 'Claro. Você está pronto para fazer o pedido agora?'},
      {'isBot': false, 'en': 'I need a few more minutes, please.', 'pt': 'Preciso de mais alguns minutos, por favor.'},
      {'isBot': true, 'en': 'Take your time. Let me know when you are ready.', 'pt': 'Fique à vontade. Me avise quando estiver pronto.'},
      {'isBot': false, 'en': 'Alright. I am ready to order.', 'pt': 'Certo. Estou pronto para pedir.'},
      {'isBot': true, 'en': 'What would you like to have today?', 'pt': 'O que você gostaria hoje?'},
      {'isBot': false, 'en': 'I will have the grilled chicken with salad.', 'pt': 'Eu vou querer o frango grelhado com salada.'},
      {'isBot': true, 'en': 'Excellent choice. Any dressing for the salad?', 'pt': 'Excelente escolha. Algum molho para a salada?'},
      {'isBot': false, 'en': 'Just olive oil and lemon, thank you.', 'pt': 'Apenas azeite e limão, obrigado(a).'},
      {'isBot': true, 'en': 'And would you like anything to drink?', 'pt': 'E gostaria de algo para beber?'},
      {'isBot': false, 'en': 'A glass of orange juice, please.', 'pt': 'Um copo de suco de laranja, por favor.'},
      {'isBot': true, 'en': 'Your food will be ready in 15 minutes.', 'pt': 'Sua comida estará pronta em 15 minutos.'},
      {'isBot': false, 'en': 'Perfect, I am very hungry.', 'pt': 'Perfeito, estou com muita fome.'},
      {'isBot': true, 'en': 'Here is your meal. Enjoy!', 'pt': 'Aqui está sua refeição. Aproveite!'},
      {'isBot': false, 'en': 'It looks delicious. Can I have the bill, please?', 'pt': 'Parece delicioso. Pode me trazer a conta, por favor?'},
      {'isBot': true, 'en': 'Certainly. How would you like to pay?', 'pt': 'Certamente. Como você gostaria de pagar?'},
      {'isBot': false, 'en': 'I will pay with a credit card.', 'pt': 'Eu pagarei com cartão de crédito.'},
    ],
  ),
  ChatScenario(
    title: 'Compras e Lojas',
    description: 'Aprenda expressões para provar e comprar produtos.',
    icon: Icons.shopping_bag_rounded,
    messages: [
      {'isBot': true, 'en': 'Hello! Can I help you find something?', 'pt': 'Olá! Posso ajudar você a encontrar algo?'},
      {'isBot': false, 'en': 'Yes, I am looking for a winter coat.', 'pt': 'Sim, estou procurando um casaco de inverno.'},
      {'isBot': true, 'en': 'Our winter coats are right over here. What size?', 'pt': 'Nossos casacos de inverno estão bem aqui. Qual tamanho?'},
      {'isBot': false, 'en': 'I usually wear medium.', 'pt': 'Eu costumo usar médio.'},
      {'isBot': true, 'en': 'Here is a nice blue one in medium. Give it a try.', 'pt': 'Aqui tem um azul bonito no tamanho médio. Experimente.'},
      {'isBot': false, 'en': 'Where are the fitting rooms?', 'pt': 'Onde ficam os provadores?'},
      {'isBot': true, 'en': 'They are in the back of the store, to the left.', 'pt': 'Ficam no fundo da loja, à esquerda.'},
      {'isBot': false, 'en': 'Thank you. I will go try it on.', 'pt': 'Obrigado. Eu vou experimentar.'},
      {'isBot': true, 'en': 'How does it fit?', 'pt': 'Como serviu?'},
      {'isBot': false, 'en': 'It is a bit too tight. Do you have a large?', 'pt': 'Ficou um pouco apertado. Você tem um grande?'},
      {'isBot': true, 'en': 'Let me check... Yes, here is a large.', 'pt': 'Deixe-me checar... Sim, aqui está um tamanho grande.'},
      {'isBot': false, 'en': 'This one fits perfectly. How much is it?', 'pt': 'Esse serviu perfeitamente. Quanto custa?'},
      {'isBot': true, 'en': 'It is fifty-five dollars.', 'pt': 'Custa cinquenta e cinco dólares.'},
      {'isBot': false, 'en': 'Do you have any discounts today?', 'pt': 'Vocês têm algum desconto hoje?'},
      {'isBot': true, 'en': 'Yes, there is a 10% discount on all winter clothes.', 'pt': 'Sim, tem um desconto de 10% em todas roupas de inverno.'},
      {'isBot': false, 'en': 'That is great. I will take it.', 'pt': 'Isso é ótimo. Eu vou levar.'},
      {'isBot': true, 'en': 'Would you like to pay with cash or card?', 'pt': 'Gostaria de pagar com dinheiro ou cartão?'},
      {'isBot': false, 'en': 'I will pay in cash. Here is sixty dollars.', 'pt': 'Pagarei em dinheiro. Aqui estão sessenta dólares.'},
      {'isBot': true, 'en': 'Here is your change and your receipt. Have a good day!', 'pt': 'Aqui está seu troco e sua nota fiscal. Tenha um bom dia!'},
      {'isBot': false, 'en': 'Thank you very much. Bye.', 'pt': 'Muito obrigado. Tchau.'},
    ],
  ),
  ChatScenario(
    title: 'Na Recepção do Hotel',
    description: 'Reservas, check-in e pedidos especiais.',
    icon: Icons.hotel_rounded,
    messages: [
      {'isBot': true, 'en': 'Welcome to the Grand Hotel. How can I help you?', 'pt': 'Bem-vindo ao Grand Hotel. Como posso ajudá-lo?'},
      {'isBot': false, 'en': 'I have a reservation under the name John Smith.', 'pt': 'Eu tenho uma reserva no nome de John Smith.'},
      {'isBot': true, 'en': 'Let me check... Ah yes, a single room for three nights.', 'pt': 'Deixe-me checar... Ah sim, um quarto de solteiro por três noites.'},
      {'isBot': false, 'en': 'That is correct. Is breakfast included?', 'pt': 'Isso está correto. O café da manhã está incluído?'},
      {'isBot': true, 'en': 'Yes, breakfast is served from 7 AM to 10 AM.', 'pt': 'Sim, o café da manhã é servido das 7 às 10 da manhã.'},
      {'isBot': false, 'en': 'Great. What floor is my room on?', 'pt': 'Ótimo. Em qual andar fica o meu quarto?'},
      {'isBot': true, 'en': 'You are on the fifth floor, room 502.', 'pt': 'Você está no quinto andar, quarto 502.'},
      {'isBot': false, 'en': 'Do you have free Wi-Fi in the room?', 'pt': 'Vocês têm Wi-Fi grátis no quarto?'},
      {'isBot': true, 'en': 'Yes, the password is written on your key card.', 'pt': 'Sim, a senha está escrita no seu cartão-chave.'},
      {'isBot': false, 'en': 'Is there a gym in the hotel?', 'pt': 'Tem academia no hotel?'},
      {'isBot': true, 'en': 'Yes, the gym is on the ground floor next to the pool.', 'pt': 'Sim, a academia fica no térreo ao lado da piscina.'},
      {'isBot': false, 'en': 'Can I request a wake-up call for tomorrow?', 'pt': 'Posso pedir uma ligação de despertar para amanhã?'},
      {'isBot': true, 'en': 'Of course. At what time would you like to wake up?', 'pt': 'Claro. A que horas gostaria de acordar?'},
      {'isBot': false, 'en': 'At six thirty AM, please.', 'pt': 'Às seis e meia da manhã, por favor.'},
      {'isBot': true, 'en': 'Noted. Do you need help with your bags?', 'pt': 'Anotado. Precisa de ajuda com as malas?'},
      {'isBot': false, 'en': 'No thanks, I can manage. Where is the elevator?', 'pt': 'Não obrigado, eu dou conta. Onde é o elevador?'},
      {'isBot': true, 'en': 'The elevators are right behind you.', 'pt': 'Os elevadores estão bem atrás de você.'},
      {'isBot': false, 'en': 'Thank you! What time is checkout?', 'pt': 'Obrigado! A que horas é o checkout?'},
      {'isBot': true, 'en': 'Checkout is at 11 AM. Enjoy your stay!', 'pt': 'O checkout é às 11 da manhã. Aproveite sua estadia!'},
      {'isBot': false, 'en': 'I will. Good day!', 'pt': 'Eu vou. Bom dia!'},
    ],
  ),
  ChatScenario(
    title: 'Direções e Transporte',
    description: 'Como chegar aos lugares e perguntar por mapas.',
    icon: Icons.directions_bus_rounded,
    messages: [
      {'isBot': true, 'en': 'Excuse me, you look a bit lost. Can I help?', 'pt': 'Com licença, você parece um pouco perdido. Posso ajudar?'},
      {'isBot': false, 'en': 'Yes, please. How do I get to the train station?', 'pt': 'Sim, por favor. Como chego à estação de trem?'},
      {'isBot': true, 'en': 'It is quite far to walk. You should take a bus.', 'pt': 'É bem longe para ir a pé. Você deveria pegar um ônibus.'},
      {'isBot': false, 'en': 'Which bus number goes there?', 'pt': 'Qual o número do ônibus que vai pra lá?'},
      {'isBot': true, 'en': 'Bus number 15 goes straight to the station.', 'pt': 'O ônibus número 15 vai direto para a estação.'},
      {'isBot': false, 'en': 'Where is the nearest bus stop?', 'pt': 'Onde é o ponto de ônibus mais próximo?'},
      {'isBot': true, 'en': 'Go straight for two blocks, then turn right.', 'pt': 'Siga reto por dois quarteirões, e então vire à direita.'},
      {'isBot': false, 'en': 'Two blocks straight, then turn right. Got it.', 'pt': 'Dois quarteirões reto, depois virar a direita. Entendido.'},
      {'isBot': true, 'en': 'Exactly. It is right in front of the supermarket.', 'pt': 'Exatamente. Fica bem na frente do supermercado.'},
      {'isBot': false, 'en': 'How much is the bus ticket?', 'pt': 'Quanto é a passagem de ônibus?'},
      {'isBot': true, 'en': 'It costs two dollars and fifty cents.', 'pt': 'Custa dois dólares e cinquenta centavos.'},
      {'isBot': false, 'en': 'Can I pay with credit card on the bus?', 'pt': 'Eu posso pagar com cartão de crédito no ônibus?'},
      {'isBot': true, 'en': 'Yes, they accept cards and cash.', 'pt': 'Sim, eles aceitam cartões e dinheiro.'},
      {'isBot': false, 'en': 'How long does the trip take?', 'pt': 'Quanto tempo dura a viagem?'},
      {'isBot': true, 'en': 'It takes about twenty minutes depending on traffic.', 'pt': 'Leva cerca de vinte minutos dependendo do trânsito.'},
      {'isBot': false, 'en': 'Is the station the last stop?', 'pt': 'A estação é a última parada?'},
      {'isBot': true, 'en': 'No, you have to get off at the fifth stop.', 'pt': 'Não, você tem que descer na quinta parada.'},
      {'isBot': false, 'en': 'Thank you for your help!', 'pt': 'Obrigado pela sua ajuda!'},
      {'isBot': true, 'en': 'You are welcome. Have a safe journey!', 'pt': 'De nada. Tenha uma jornada segura!'},
      {'isBot': false, 'en': 'Have a good day!', 'pt': 'Tenha um bom dia!'},
    ],
  ),
  ChatScenario(
    title: 'Trabalho e Entrevista',
    description: 'Falando sobre carreira e responder entrevistas.',
    icon: Icons.work_rounded,
    messages: [
      {'isBot': true, 'en': 'Good morning. Please, take a seat. I am Mr. Miller.', 'pt': 'Bom dia. Por favor, sente-se. Eu sou o Sr. Miller.'},
      {'isBot': false, 'en': 'Good morning, Mr. Miller. Nice to meet you.', 'pt': 'Bom dia, Sr. Miller. Prazer em conhecê-lo.'},
      {'isBot': true, 'en': 'Can you tell me a little about yourself?', 'pt': 'Pode me falar um pouco sobre você?'},
      {'isBot': false, 'en': 'Sure. I am an experienced software engineer.', 'pt': 'Claro. Sou um engenheiro de software experiente.'},
      {'isBot': true, 'en': 'Where did you work previously?', 'pt': 'Onde você trabalhava anteriormente?'},
      {'isBot': false, 'en': 'I worked at TechCorp for three years.', 'pt': 'Eu trabalhei na TechCorp por três anos.'},
      {'isBot': true, 'en': 'Why did you leave your last job?', 'pt': 'Por que você saiu do seu último emprego?'},
      {'isBot': false, 'en': 'I am looking for a new challenge.', 'pt': 'Estou em busca de um novo desafio.'},
      {'isBot': true, 'en': 'What are your greatest strengths?', 'pt': 'Quais são as suas maiores qualidades?'},
      {'isBot': false, 'en': 'I am a fast learner and a good team player.', 'pt': 'Eu aprendo rápido e trabalho bem em equipe.'},
      {'isBot': true, 'en': 'Do you have any weakness?', 'pt': 'Você tem algum ponto fraco?'},
      {'isBot': false, 'en': 'Sometimes I focus too much on details.', 'pt': 'Às vezes, eu me concentro demais nos detalhes.'},
      {'isBot': true, 'en': 'Are you comfortable working under pressure?', 'pt': 'Você fica confortável trabalhando sob pressão?'},
      {'isBot': false, 'en': 'Yes, I handle pressure very well.', 'pt': 'Sim, eu lido muito bem com pressão.'},
      {'isBot': true, 'en': 'What are your salary expectations?', 'pt': 'Quais são as suas expectativas salariais?'},
      {'isBot': false, 'en': 'I would like to discuss it after knowing more.', 'pt': 'Eu gostaria de discutir isso após saber mais.'},
      {'isBot': true, 'en': 'That is fair. Do you have any questions for me?', 'pt': 'Isso é justo. Você tem alguma pergunta para mim?'},
      {'isBot': false, 'en': 'Yes. What is the team like?', 'pt': 'Sim. Como é a equipe?'},
      {'isBot': true, 'en': 'We have a very collaborative and friendly team.', 'pt': 'Nós temos uma equipe muito prestativa e amigável.'},
      {'isBot': false, 'en': 'That sounds perfect. Thank you.', 'pt': 'Isso soa perfeito. Obrigado.'},
    ],
  ),
  ChatScenario(
    title: 'No Médico',
    description: 'Como explicar sintomas de forma clara e simples.',
    icon: Icons.local_hospital_rounded,
    messages: [
      {'isBot': true, 'en': 'Hello. What seems to be the problem today?', 'pt': 'Olá. Qual parece ser o problema hoje?'},
      {'isBot': false, 'en': 'I have a terrible headache and fever.', 'pt': 'Eu tenho uma terrível dor de cabeça e febre.'},
      {'isBot': true, 'en': 'How long have you been feeling like this?', 'pt': 'Há quanto tempo você tem se sentido assim?'},
      {'isBot': false, 'en': 'Since yesterday morning.', 'pt': 'Desde ontem de manhã.'},
      {'isBot': true, 'en': 'Do you have a sore throat or cough?', 'pt': 'Você tem dor de garganta ou tosse?'},
      {'isBot': false, 'en': 'Yes, my throat hurts a lot.', 'pt': 'Sim, minha garganta dói muito.'},
      {'isBot': true, 'en': 'Let me check your temperature. Open your mouth, please.', 'pt': 'Deixe-me checar sua temperatura. Abra a boca, por favor.'},
      {'isBot': false, 'en': 'Ahhhh. Is it high?', 'pt': 'Ahhhh. Está alta?'},
      {'isBot': true, 'en': 'Yes, it is 39 degrees. You have a flu.', 'pt': 'Sim, está 39 graus. Você está com a gripe.'},
      {'isBot': false, 'en': 'Oh no. What should I do?', 'pt': 'Ah não. O que eu deveria fazer?'},
      {'isBot': true, 'en': 'You need to rest and drink plenty of water.', 'pt': 'Você precisa descansar e beber bastante água.'},
      {'isBot': false, 'en': 'Do I need any medicine?', 'pt': 'Eu preciso de algum remédio?'},
      {'isBot': true, 'en': 'I will prescribe you some pain relievers.', 'pt': 'Eu vou receitar alguns analgésicos para você.'},
      {'isBot': false, 'en': 'How often should I take the medicine?', 'pt': 'Com qual frequência eu devo tomar o remédio?'},
      {'isBot': true, 'en': 'Take one pill every eight hours after meals.', 'pt': 'Tome um comprimido a cada oito horas após as refeições.'},
      {'isBot': false, 'en': 'Are there any side effects?', 'pt': 'Existem efeitos colaterais?'},
      {'isBot': true, 'en': 'It might make you feel a bit sleepy.', 'pt': 'Pode fazer você se sentir um pouco sonolento.'},
      {'isBot': false, 'en': 'Understood. Should I come back next week?', 'pt': 'Entendido. Eu devo voltar semana que vem?'},
      {'isBot': true, 'en': 'Come back only if you don’t feel better in three days.', 'pt': 'Volte apenas se não se sentir melhor em três dias.'},
      {'isBot': false, 'en': 'Thank you, doctor. Have a good day.', 'pt': 'Obrigado, doutor. Tenha um bom dia.'},
    ],
  ),
  ChatScenario(
    title: 'Alugando um Carro',
    description: 'Documentos e seguros automotivos essenciais.',
    icon: Icons.car_rental_rounded,
    messages: [
      {'isBot': true, 'en': 'Hello! Welcome to Easy Car Rentals.', 'pt': 'Olá! Bem-vindo a Aluguéis de Carros Rápidos.'},
      {'isBot': false, 'en': 'Hi! I would like to rent a car for a week.', 'pt': 'Oi! Eu gostaria de alugar um carro por uma semana.'},
      {'isBot': true, 'en': 'Sure. Do you have a reservation?', 'pt': 'Claro. Você tem uma reserva?'},
      {'isBot': false, 'en': 'No, I do not. Do you have any cars available?', 'pt': 'Não, eu não tenho. Você tem algum carro disponível?'},
      {'isBot': true, 'en': 'Yes, we have a sedan and a compact car.', 'pt': 'Sim, nós temos um sedã e um carro compacto.'},
      {'isBot': false, 'en': 'I will take the compact car.', 'pt': 'Eu vou ficar com o carro compacto.'},
      {'isBot': true, 'en': 'Great. I need to see your driver\'s license and credit card.', 'pt': 'Ótimo. Eu preciso ver a sua carteira de motorista e o cartão de crédito.'},
      {'isBot': false, 'en': 'Here they are. Is the insurance included?', 'pt': 'Aqui estão. O seguro está incluído?'},
      {'isBot': true, 'en': 'Basic insurance is included. Would you like full coverage?', 'pt': 'O seguro básico está. Gostaria da cobertura completa?'},
      {'isBot': false, 'en': 'How much is the full coverage?', 'pt': 'Quanto custa a cobertura completa?'},
      {'isBot': true, 'en': 'It is an extra fifteen dollars per day.', 'pt': 'Custa quinze dólares adicionais por dia.'},
      {'isBot': false, 'en': 'Okay, I will add the full coverage.', 'pt': 'Ok, eu vou adicionar a cobertura completa.'},
      {'isBot': true, 'en': 'The total is two hundred dollars. Can I swipe your card?', 'pt': 'O total é duzentos dólares. Posso passar seu cartão?'},
      {'isBot': false, 'en': 'Yes, go ahead.', 'pt': 'Sim, vá em frente.'},
      {'isBot': true, 'en': 'Please sign here. The car is parked outside.', 'pt': 'Por favor, assine aqui. O carro está estacionado lá fora.'},
      {'isBot': false, 'en': 'Is the gas tank full?', 'pt': 'O tanque de gasolina está cheio?'},
      {'isBot': true, 'en': 'Yes, please return it with a full tank.', 'pt': 'Sim, por favor devolva-o com tanque cheio.'},
      {'isBot': false, 'en': 'What happens if I return it late?', 'pt': 'O que acontece se eu entregar atrasado?'},
      {'isBot': true, 'en': 'There is a fee of ten dollars per hour over time.', 'pt': 'Há uma taxa de dez dólares por hora de atraso.'},
      {'isBot': false, 'en': 'Alright. Here are the keys. Thanks!', 'pt': 'Tudo bem. Aqui estão as chaves. Obrigado!'},
    ],
  ),
  ChatScenario(
    title: 'Hobbies e Entretenimento',
    description: 'Falando sobre fim de semana e o que você gosta.',
    icon: Icons.movie_rounded,
    messages: [
      {'isBot': true, 'en': 'Hey there! How was your weekend?', 'pt': 'E aí! Como foi o seu final de semana?'},
      {'isBot': false, 'en': 'It was great! I went to the cinema.', 'pt': 'Foi ótimo! Eu fui para o cinema.'},
      {'isBot': true, 'en': 'Really? What movie did you watch?', 'pt': 'Sério? Qual filme você assistiu?'},
      {'isBot': false, 'en': 'I watched a new action movie.', 'pt': 'Eu assisti a um novo filme de ação.'},
      {'isBot': true, 'en': 'Was it good? I love action movies.', 'pt': 'Foi bom? Eu amo filmes de ação.'},
      {'isBot': false, 'en': 'Yes, the special effects were amazing.', 'pt': 'Sim, os efeitos especiais eram incríveis.'},
      {'isBot': true, 'en': 'What else do you like to do in your free time?', 'pt': 'O que mais você gosta de fazer no tempo livre?'},
      {'isBot': false, 'en': 'I love playing video games and reading.', 'pt': 'Eu amo jogar video game e ler.'},
      {'isBot': true, 'en': 'Nice! What kind of books do you read?', 'pt': 'Legal! Que tipo de livros você lê?'},
      {'isBot': false, 'en': 'I enjoy reading fantasy and sci-fi books.', 'pt': 'Eu gosto de ler livros de fantasia e ficção.'},
      {'isBot': true, 'en': 'I prefer reading biographies. Do you play sports?', 'pt': 'Eu prefiro biografias. Você pratica esportes?'},
      {'isBot': false, 'en': 'Yes, I play soccer every Sunday.', 'pt': 'Sim, eu jogo futebol todo domingo.'},
      {'isBot': true, 'en': 'Soccer is very popular! I prefer running.', 'pt': 'Futebol é muito popular! Eu prefiro correr.'},
      {'isBot': false, 'en': 'Running is excellent for health.', 'pt': 'Correr é excelente para a saúde.'},
      {'isBot': true, 'en': 'We should go to the park this weekend.', 'pt': 'Nós deveríamos ir ao parque este fim de semana.'},
      {'isBot': false, 'en': 'That sounds like a great idea.', 'pt': 'Isso parece uma ótima ideia.'},
      {'isBot': true, 'en': 'Let us invite our friends too.', 'pt': 'Vamos convidar nossos amigos também.'},
      {'isBot': false, 'en': 'I will call them tonight.', 'pt': 'Eu ligarei para eles hoje à noite.'},
      {'isBot': true, 'en': 'Great. I am looking forward to it.', 'pt': 'Ótimo. Eu estou ansioso por isso.'},
      {'isBot': false, 'en': 'Me too. Talk to you later!', 'pt': 'Eu também. Falo com você depois!'},
    ],
  ),
];
